version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=Adev123..
      - MYSQL_DATABASE=order_db
    ports:
      - "3307:3306"
    container_name: mymysqlcontainer
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
